apiCersion: apps/v1
kind: Deplyment
metadata:
  namespace: springboot
  name: my-first-spring-deployment
  labels:
    name: my-first-spring-boot
spec:
  selector:
    matchLabels:
      name: my-first-spring-boot
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: my-first-spring-boot
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-master
      containers:
      - name: my-first-spring-boot
        image: gompangii/myfirstspringboot
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: http
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
  